export const navLinks = [
  {
    id: 0,
    name: "Home",
    link: "/",
  },
  {
    id: 1,
    name: "Restaurants",
    link: "/restaurants",
  },
  {
    id: 2,
    name: "My orders",
    link: "/orders",
  },
];

export const categories = [
  { id: 0, name: "Pizza", img: "/categories/pizza.png" },
  { id: 1, name: "Burger", img: "/categories/hamburger.png" },
  { id: 2, name: "BBQ", img: "/categories/skewer.png" },
  { id: 3, name: "Chicken", img: "/categories/fried-chicken.png" },
  { id: 5, name: "Rice", img: "/categories/fried-rice.png" },
  { id: 4, name: "Drinks", img: "/categories/soft-drink.png" },
];

export const foodObj = {
  id: 1,
  name: "Chicken BBQ",
  restaurant: "Royal Sushi House",
  price: 80,
  discount: 10,
  imageUrl: "",
  rating: "4.8",
};

export const restaurantArr = [
  {
    id: "1",
    imageUrl: "/products/restaurants/img.jpg",
    avgMinutes: "30-40 min",
    name: "Royal Pizza House",
    category: { name: "Pizza", img: "/categories/pizza.png" },
    rating: "5.0",
    reviews: [],
    location: "Osu",
    phone: "+233202342343",
    orderCount: 80,
  },
  {
    id: "2",
    imageUrl: "/products/restaurants/rest-1.jpg",
    avgMinutes: "30-40 min",
    name: "Calabasa",
    category: { name: "Pizza", img: "/categories/pizza.png" },
    rating: "4.5",
    reviews: [],
    location: "Osu",
    phone: "+233202342343",
    orderCount: 80,
  },
  {
    id: "3",
    imageUrl: "/products/restaurants/rest-2.jpg",
    avgMinutes: "30-40 min",
    name: "Flavor Fusion",
    category: { name: "Pizza", img: "/categories/pizza.png" },
    rating: "5.0",
    reviews: [],
    location: "Osu",
    phone: "+233202342343",
    orderCount: 80,
  },
  {
    id: "4",
    imageUrl: "/products/restaurants/rest-3.jpg",
    avgMinutes: "30-40 min",
    name: "The Charming Bistro",
    category: { name: "Pizza", img: "/categories/pizza.png" },
    rating: "4.0",
    reviews: [],
    location: "Osu",
    phone: "+233202342343",
    orderCount: 80,
  },
  {
    id: "5",
    imageUrl: "/products/restaurants/rest-4.jpg",
    avgMinutes: "30-40 min",
    name: "The Veggie Patch",
    category: { name: "Pizza", img: "/categories/pizza.png" },
    rating: "5.0",
    reviews: [],
    location: "Osu",
    phone: "+233202342343",
    orderCount: 80,
  },
  {
    id: "6",
    imageUrl: "/products/restaurants/rest-5.jpg",
    avgMinutes: "30-40 min",
    name: "The Juicy Burger",
    category: { name: "Pizza", img: "/categories/pizza.png" },
    rating: "5.0",
    reviews: [],
    location: "Osu",
    phone: "+233202342343",
    orderCount: 80,
  },
];
